[build]
  publish = "."
  functions = "netlify/functions"
  command = "node build.js"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  functions = "netlify/functions"

[template.environment]
  NETLIFY_IDENTITY_ENABLED = "true"
  STRIPE_PUBLISHABLE_KEY = "Enter your Stripe publishable key (starts with pk_)"

[[plugins]]
package = "@netlify/plugin-functions-install-core" 